[package]
name = "generativelanguage-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.163"
tokio = { version = "1.15.0", features = ["full"] }

